### ISSUE TITLE
How to test if the server is running all right

### ISSUE THREAD

**Issue by TiagoXavi** [juce/fiveserver#4]
Hi guys,

I am trying to run the fiveserver-0.4.8 for windows with no success.

- [x] I reach the password screen on others servers (public) (after this I think that the game is not the problem)
- [x] The web server is working fine on ports 8190 and 8191
- [x] I tried to redirect the hosts file to localhost IP and public IP. No one worked 

There are any kind of test that I can do to see what is the problem?

Can't pass this screen: 

![image](https://user-images.githubusercontent.com/22452335/100685304-dfd0ac00-335a-11eb-8a4d-1e9fdc317716.png)

**Comment by moth1995** [comment]
have you added the stun server into the host file?
also if you're trying to reach it from your private network you'll need to do something as a hairping service in your router

**Comment by lugishr** [comment]
Hello guys,
Did you manage to solve this issue ?
I also cannot pass that screen mentioned in the first comment.
I'm running Fiveserver 0.4.11 in Ubuntu Virtualbox VM. Host operating system is Windows 10.
Additionally, in `sixserver.yaml` I changed `ServerIP` to IP of VM (because when done automatically, then the IP was my public IP which is in this case not correct).
sixserver service is running fine on the guest VM.
The communication between host and guest VM is possible, I tested in web browser and I am able to open web pages on 8191 and 8190.
Also I used telnet to test access to all needed ports (from host to guest VM) and this works well.

I set `hosts` file like this:
<VM_IP> we9stun.winning-eleven.net
<VM_IP> pes6gate-ec.winning-eleven.net

I used Resource Monitor and saw that PES6.exe is trying to reach we9stun.winning-eleven.net which is correctly resolved to IP of VM - but I see only Sent data, Received data is 0.

Any suggestions how to continue from this point ?

Thanks.

**Comment by TiagoXavi** [comment]
Hello lugishr,

I still didn't get it working for PES6.
But I get it working for WE9LE. It comes with kitserver network plugin and works (you need to put your IP in network.cfg).
Works even with local IP 127.0.0.1
I didn't test kitserver network plugin for PES6 because my anti-virus is very sure that it is a malicious file when I try to download. But the WE9 version safe... AV things

**Comment by moth1995** [comment]
Hi guys, first, if you want to test it over your lan network, you need to understand that the server needs to communicate over the stun server too and you will need this hairpin nat, i did it over mikrotik for my home testing too, i dont know how it should be done in your routers

https://wiki.mikrotik.com/wiki/Hairpin_NAT

there i leave you the guide i use for mikrotik, maybe you can do it over your own routers

then about how to configure the host file

if you solve the hairpin issue then

217.10.68.152 we9stun.winning-eleven.net #you can use any stun server, this one is working
<VM_Private_IP> pes6gate-ec.winning-eleven.net #example 192.168.1.5

then in your sixserver.yaml just leave it to be automatic, its okay that the server use the public ip even if you're over the same network, its because that's how the stun protocol works, i recommend you to read more about that before too and fix the hair pin nat

and about the modules, i test it over my servers and it works properly, for pes6 there's not such a thing as a network module, you need yo use host file

**Comment by moth1995** [comment]
asi it may help i leave you below the rules i use at my home

add action=dst-nat chain=dstnat comment="Hairping service PES 6" disabled=yes dst-address=!192.168.10.0/24 dst-address-type=local dst-port=8190,10881,20200,20201,20202,20203 protocol=tcp \
    to-addresses=192.168.10.102
add action=masquerade chain=srcnat disabled=yes dst-port=8190,10881,20200,20201,20202,20203 protocol=tcp src-address=192.168.10.0/24

to put more in context, my local network its 192.168.10.0/24 and this is only for the pes6 server, if you want pes5 too you need to add the corresponding ports

that's all i can do to help you guys, everything else depends on you!

**Comment by lugishr** [comment]
Thank you for all the replies! All I did was changing the IP address of STUN server in my `hosts` file and now it seems to be working (at least the connection).

**Comment by juce** [comment]
closing, as this seems resolved now
